[package]
name = "alian"
version = "0.1.0"
authors = ["lll1412 <920595557@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
panic = "abort"
#lto = "fat"
codegen-units = 1
#incremental = true

[dependencies]